[project]
name = "graph-trip"
version = "0.1.0"
description = "TD notebook on BFS, DFS and shortest path algorithms with Paris road network"
requires-python = ">=3.11"
dependencies = [
    "osmnx>=1.6.0",
    "networkx>=3.0",
    "plotly>=5.0.0",
    "matplotlib>=3.7.0",
    "numpy>=1.24.0",
    "ipykernel>=6.0.0",
    "geopandas>=0.13.0",
    "jupyterlab",
    "streamlit>=1.28.0",
    "scikit-learn>=1.7.2",
    "node2vec>=0.5.0",
    "opentsne>=1.0.4",
]
